service: hr-bot

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
iamRoleStatements:
  - Effect: Allow
    Action:
      - "ssm:GetParameters"
    Resource: "arn:aws:ssm:ap-southeast-1:453517329787:parameter/*"
functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: GET
  ssmParams:
    handler: handler.getSsmParams
    events:
    - http:
        path: ssm-params
        method: GET
plugins:
  - serverless-offline
